[package]
name = "concert-std"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
bumpalo = "3.5.0"
concert-std-derive = { path = "../concert-std-derive" }
immutable-map = "0.1.2"
solana-program = "~1.10.35"
borsh = "0.9.3"
borsh-derive = "0.9.1"
